### ISSUE TITLE
内核

### ISSUE THREAD

**Issue by cnzhoutao** [DingMouRen/DingDingMusic#1]
内核好像只支持x86的，不支持ARM的呢，所以在虚拟机上不做处理运行不了。

**Comment by DingMouRen** [comment]
是的，真机才看可以的，你有什么办法，在android studio自带的模拟器上运行吗

**Comment by cnzhoutao** [comment]
自带的我不知道哎，Genymotion是可以的，需要Genymotion-ARM-Translation这个文件。如果能把arm的so文件也放进去就更好了

**Comment by DingMouRen** [comment]
Genymotion的那个文件我用过，Genymotion这个模拟器的视图不是很好看，比如状态栏颜色。我想把手机操作的流程制作成gif图，用来展示app，用android studio 自带的模拟器制作的gif清晰，但是不支持arm,这个gif是通过手机录屏，将视频制作成的gif，所以很模糊，你有什么好东西可以用的O(∩_∩)O
